vich_uploader:
    db_driver: orm

    mappings:
        housing_images:
            # La valeur de la clé uri_prefix doit correspondre à la fin
            # de la valeur de la clé upload_destination
            uri_prefix: /uploads/housing
            upload_destination: '%kernel.project_dir%/public/uploads/housing'
